backend:
  name: git-gateway
  branch: pl
media_folder: "media"
local_backend: true
collections:
  - name: "home"
    label: "Home"
    files:
      - label: "Home"
        name: "home"
        file: "content/index.md"
        fields:
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "home",
            }
          - {label: Tagline, name: tagline, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown} 
          - label: "Topics"
            name: "topics"
            widget: "list"
            fields:
            - { label: Title, name: title, widget: string }
            - { label: Image, name: image, widget: image }
            - { label: Link, name: link, widget: string }
  - name: "theory"
    label: "All Articles"
    folder: "content/theory"
    create: true
    identifier_field: name
    slug: "{{key}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "article",
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "hidden",
          default: "theory",
        }
      - {
          label: "Key (Short name of the theory. Can't be changed after the theory is created.)",
          name: "key",
          widget: "string",
        }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Sort order", name: "sortOrder", widget: "number" }
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "theoryCategories"
        required: true
        displayFields: ["name"]
        valueField: "key"
        searchFields: ["name"]
      - { label: "Introduction", name: "intro", widget: "markdown", required: false }
      - { label: "A new perspective", name: "perspective", widget: "markdown", required: false }
      - { label: "In Practice", name: "inPractice", widget: "markdown", required: false }
      - { label: "Body (not used anymore)", name: "body", widget: "markdown", required: false }
      - label: "FAQ"
        name: "faq"
        widget: "list"
        fields:
          - { label: Question, name: question, widget: string }
          - { label: Answer, name: answer, widget: markdown, minimal: true }
      - label: "Related Theory"
        name: "relatedTheory"
        widget: "relation"
        collection: "theory"
        required: false
        displayFields: ["name"]
        valueField: "key"
        searchFields: ["name"]
        multiple: true
        optionsLength: 1000
  - name: "theoryCategories"
    hide: true
    label: "Theory Categories"
    folder: "content/theoryCategories"
    create: false
    identifier_field: name
    fields:
      - {
          label: "Tags",
          name: "tags",
          widget: "hidden",
          default: "practicesTheoryCategories",
        }
      - {
          label: "Key (Short name of the category. Can't be changed after the category is created.)",
          name: "key",
          widget: "string",
        }
      - { label: "Name", name: "name", widget: "string" }
  - name: "cases"
    label: "Case Studies"
    folder: "content/cases"
    create: true
    identifier_field: name
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "case" }
      - {
          label: "Tags",
          name: "tags",
          widget: "hidden",
          default: "cases",
        }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime"}
      - {
          label: "Introduction",
          name: "introduction",
          widget: "markdown",
          minimal: true,
        }
      - {
          label: "Industry",
          name: "industry",
          widget: "select",
          options: [
            "A. Produkty rolne, leśne i rybołówstwo", 
            "B. Górnictwo i wydobycie",
            "C. Przemysł",
            "D. Elektryczność, gaz, para i klimatyzacja",
            "E. Zaopatrzenie w wodę; gospodarka komunalna, gospodarka odpadami i rekultywacja",
            "F. Konstrukcje i roboty budowlane",
            "G. Handel hurtowy i detaliczny; usługi serwisowe pojazdów samochodowych i motocyklów",
            "H. Usługi transportowe i magazynowe",
            "I. Zakwaterowanie i usługi gastronomiczne",
            "J. Usługi informacyjne i komunikacyjne",
            "K. Usługi finansowe i i ubezpieczeniowe",
            "L. Obsługa nieruchomości",
            "M. Usługi profesjonalne, naukowe i techniczne",
            "N. Usługi administracji i wsparcia",
            "O. Administracja publiczna i obronna; obowiązkowe usługi ubezpieczeń społecznych",
            "P. Edukacja",
            "Q. Ochrona zdrowia i pomoc społeczna",
            "R. Usługi kulturalne, rozrywkowe i rekreacyjne",
            "S. Inne usługi",
            "T. Gospodarstwa domowe zatrudniające pracowników; gospodarstwa domowe produkujące wyroby i świadczące usługi na własne potrzeby",
            "U. Usługi świadczone przez organizacje i zespoły eksterytorialne",
            "V. Inne"
            ],
        }
      - {
          label: "Geography",
          name: "geography",
          widget: "select",
          options: ["Brazylia", "Kanada", "Chiny", "Egipt", "Francja", "Niemcy", "Globalna", "Indie", "Japonia", "Maroko", "Niderlandy", "Nowa Zelandia", "Filipiny", "Szwajcaria", "Turcja", "Wielka Brytania", "USA"],
        }
      - {
          label: "Company size",
          name: "companySize",
          widget: "select",
          options: ["1-100", "101-200", "201-500", "> 500"],
        }
      - {
          label: "Profit",
          name: "profit",
          widget: "select",
          options: ["Profit", "non-profit"],
        }
      - label: "Theory"
        name: "theory"
        widget: "list"
        fields:
          - {
              label: Topic,
              name: topic,
              widget: relation,
              collection: "theory",
              displayFields: ["name"],
              valueField: "key",
              searchFields: ["name"],
            }
          - { label: Title, name: title, widget: string }
          - { label: Content, name: content, widget: markdown, minimal: true }
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    identifier_field: name
    slug: "{{name}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "content",
        }
      - {label: Title, name: name, widget: string}
      - {label: Body, name: body, widget: markdown} 
  - label: "Configuration"
    name: "configuration"
    files:
      - label: "Footer"
        name: "footer"
        file: "_data/footer.json"
        fields:
          - label: "Footer Links"
            name: "footerLinks"
            widget: "list"
            fields:
            - { label: Title, name: title, widget: string }
            - { label: Link, name: link, widget: string }
