backend:
  name: git-gateway
  branch: fr
media_folder: "media"
local_backend: true
collections:
  - name: "home"
    label: "Home"
    files:
      - label: "Home"
        name: "home"
        file: "content/index.md"
        fields:
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "home",
            }
          - {label: Tagline, name: tagline, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown} 
          - label: "Topics"
            name: "topics"
            widget: "list"
            fields:
            - { label: Title, name: title, widget: string }
            - { label: Image, name: image, widget: image }
            - { label: Link, name: link, widget: string }
  - name: "theory"
    label: "All Articles"
    folder: "content/theory"
    create: true
    identifier_field: name
    slug: "{{key}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "article",
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "hidden",
          default: "theory",
        }
      - {
          label: "Key (Short name of the theory. Can't be changed after the theory is created.)",
          name: "key",
          widget: "string",
        }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Sort order", name: "sortOrder", widget: "number" }
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "theoryCategories"
        required: true
        displayFields: ["name"]
        valueField: "key"
        searchFields: ["name"]
      - { label: "Introduction", name: "intro", widget: "markdown", required: false }
      - { label: "A new perspective", name: "perspective", widget: "markdown", required: false }
      - { label: "In Practice", name: "inPractice", widget: "markdown", required: false }
      - { label: "Body (not used anymore)", name: "body", widget: "markdown", required: false }
      - label: "FAQ"
        name: "faq"
        widget: "list"
        fields:
          - { label: Question, name: question, widget: string }
          - { label: Answer, name: answer, widget: markdown, minimal: true }
      - label: "Related Theory"
        name: "relatedTheory"
        widget: "relation"
        collection: "theory"
        required: false
        displayFields: ["name"]
        valueField: "key"
        searchFields: ["name"]
        multiple: true
        optionsLength: 1000
  - name: "theoryCategories"
    hide: true
    label: "Theory Categories"
    folder: "content/theoryCategories"
    create: false
    identifier_field: name
    fields:
      - {
          label: "Tags",
          name: "tags",
          widget: "hidden",
          default: "theoryCategories",
        }
      - {
          label: "Key (Short name of the category. Can't be changed after the category is created.)",
          name: "key",
          widget: "string",
        }
      - { label: "Name", name: "name", widget: "string" }
  - name: "cases"
    label: "Case Studies"
    folder: "content/cases"
    create: true
    identifier_field: name
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "case" }
      - {
          label: "Tags",
          name: "tags",
          widget: "hidden",
          default: "cases",
        }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime"}
      - {
          label: "Introduction",
          name: "introduction",
          widget: "markdown",
          minimal: true,
        }
      - {
          label: "Industry",
          name: "industry",
          widget: "select",
          options: [
            "A : AGRICULTURE, SYLVICULTURE ET PÊCHE", 
            "B : INDUSTRIES EXTRACTIVES",
            "C : INDUSTRIE MANUFACTURIÈRE",
            "D : ÉLECTRICITÉ, GAZ, VAPEUR ET AIR CONDITIONNÉ",
            "E : PRODUCTION ET DISTRIBUTION D’EAU ; ASSAINISSEMENT, GESTION DES DÉCHETS ET DÉPOLLUTION",
            "F : CONSTRUCTIONS ET TRAVAUX DE CONSTRUCTION",
            "G : COMMERCE ; RÉPARATION D’AUTOMOBILES ET DE MOTOCYCLES",
            "H : SERVICES DE TRANSPORT ET D’ENTREPOSAGE",
            "I : SERVICES D’HÉBERGEMENT ET DE RESTAURATION",
            "J : SERVICES D’INFORMATION ET DE COMMUNICATION",
            "K : SERVICES FINANCIERS ET ASSURANCES",
            "L : SERVICES IMMOBILIERS",
            "M : SERVICES PROFESSIONNELS, SCIENTIFIQUES ET TECHNIQUES",
            "N : SERVICES ADMINISTRATIFS ET D’ASSISTANCE",
            "O : ADMINISTRATION PUBLIQUE",
            "P : ENSEIGNEMENT",
            "Q : SANTÉ HUMAINE ET ACTION SOCIALE",
            "R : ARTS, SPECTACLES ET ACTIVITÉS RÉCRÉATIVES",
            "S : AUTRES SERVICES",
            "T : ACTIVITÉS DES MÉNAGES EN TANT QU’EMPLOYEURS ; ACTIVITÉS INDIFFÉRENCIÉES DES MÉNAGES EN TANT QUE PRODUCTEURS DE BIENS ET SERVICES POUR USAGE PROPRE",
            "U : SERVICES EXTRA-TERRITORIAUX",
            "V: AUTRES"
            ],
        }
      - {
          label: "Géographie",
          name: "geography",
          widget: "select",
          options: ["Allemagne", "Brésil", "Canada", "Chine", "Egypte", "France", "Global", "Inde", "Japon", "Maroc", "Nouvelle Zélande", "Pays-Bas", "Philippines", "Royaume Uni", "Suisse", "USA"],
        }
      - {
          label: "Taille de l'organisation",
          name: "companySize",
          widget: "select",
          options: ["1-100", "101-200", "201-500", "> 500"],
        }
      - {
          label: "Profit",
          name: "profit",
          widget: "select",
          options: ["à but lucratif", "à but non lucratif"],
        }
      - label: "Theory"
        name: "theory"
        widget: "list"
        fields:
          - {
              label: Topic,
              name: topic,
              widget: relation,
              collection: "theory",
              displayFields: ["name"],
              valueField: "key",
              searchFields: ["name"],
            }
          - { label: Title, name: title, widget: string }
          - { label: Content, name: content, widget: markdown, minimal: true }
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    identifier_field: name
    slug: "{{name}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "content",
        }
      - {label: Title, name: name, widget: string}
      - {label: Body, name: body, widget: markdown} 
  - label: "Configuration"
    name: "configuration"
    files:
      - label: "Footer"
        name: "footer"
        file: "_data/footer.json"
        fields:
          - label: "Footer Links"
            name: "footerLinks"
            widget: "list"
            fields:
            - { label: Title, name: title, widget: string }
            - { label: Link, name: link, widget: string }
